// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyState int32

const (
	PolicyState_POLICY_STATE_UNSPECIFIED PolicyState = 0
	// Policy present, loaded and actively running.
	PolicyState_POLICY_STATE_READY PolicyState = 1
	// Agent attempted to load/apply policy and it failed.
	PolicyState_POLICY_STATE_ERROR PolicyState = 2
)

// Enum value maps for PolicyState.
var (
	PolicyState_name = map[int32]string{
		0: "POLICY_STATE_UNSPECIFIED",
		1: "POLICY_STATE_READY",
		2: "POLICY_STATE_ERROR",
	}
	PolicyState_value = map[string]int32{
		"POLICY_STATE_UNSPECIFIED": 0,
		"POLICY_STATE_READY":       1,
		"POLICY_STATE_ERROR":       2,
	}
)

func (x PolicyState) Enum() *PolicyState {
	p := new(PolicyState)
	*p = x
	return p
}

func (x PolicyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (PolicyState) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[0]
}

func (x PolicyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyState.Descriptor instead.
func (PolicyState) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type PolicyMode int32

const (
	PolicyMode_POLICY_MODE_UNSPECIFIED PolicyMode = 0
	// Policy monitor mode
	PolicyMode_POLICY_MODE_MONITOR PolicyMode = 1
	// Policy protect mode
	PolicyMode_POLICY_MODE_PROTECT PolicyMode = 2
)

// Enum value maps for PolicyMode.
var (
	PolicyMode_name = map[int32]string{
		0: "POLICY_MODE_UNSPECIFIED",
		1: "POLICY_MODE_MONITOR",
		2: "POLICY_MODE_PROTECT",
	}
	PolicyMode_value = map[string]int32{
		"POLICY_MODE_UNSPECIFIED": 0,
		"POLICY_MODE_MONITOR":     1,
		"POLICY_MODE_PROTECT":     2,
	}
)

func (x PolicyMode) Enum() *PolicyMode {
	p := new(PolicyMode)
	*p = x
	return p
}

func (x PolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (PolicyMode) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[1]
}

func (x PolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyMode.Descriptor instead.
func (PolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type ListPoliciesStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusRequest) Reset() {
	*x = ListPoliciesStatusRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusRequest) ProtoMessage() {}

func (x *ListPoliciesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type PolicyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PolicyState            `protobuf:"varint,1,opt,name=state,proto3,enum=runtimeenforcer.agent.v1.PolicyState" json:"state,omitempty"`
	Mode          PolicyMode             `protobuf:"varint,2,opt,name=mode,proto3,enum=runtimeenforcer.agent.v1.PolicyMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStatus) Reset() {
	*x = PolicyStatus{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatus) ProtoMessage() {}

func (x *PolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatus.ProtoReflect.Descriptor instead.
func (*PolicyStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyStatus) GetState() PolicyState {
	if x != nil {
		return x.State
	}
	return PolicyState_POLICY_STATE_UNSPECIFIED
}

func (x *PolicyStatus) GetMode() PolicyMode {
	if x != nil {
		return x.Mode
	}
	return PolicyMode_POLICY_MODE_UNSPECIFIED
}

type ListPoliciesStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Policies      map[string]*PolicyStatus `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusResponse) Reset() {
	*x = ListPoliciesStatusResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusResponse) ProtoMessage() {}

func (x *ListPoliciesStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ListPoliciesStatusResponse) GetPolicies() map[string]*PolicyStatus {
	if x != nil {
		return x.Policies
	}
	return nil
}

type ScrapeViolationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeViolationsRequest) Reset() {
	*x = ScrapeViolationsRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeViolationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeViolationsRequest) ProtoMessage() {}

func (x *ScrapeViolationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeViolationsRequest.ProtoReflect.Descriptor instead.
func (*ScrapeViolationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type ViolationRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PodName        string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName  string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ExecutablePath string                 `protobuf:"bytes,4,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	NodeName       string                 `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Action         string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	PolicyName     string                 `protobuf:"bytes,7,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	Count          uint32                 `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ViolationRecord) Reset() {
	*x = ViolationRecord{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViolationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViolationRecord) ProtoMessage() {}

func (x *ViolationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViolationRecord.ProtoReflect.Descriptor instead.
func (*ViolationRecord) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ViolationRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ViolationRecord) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ViolationRecord) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ViolationRecord) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *ViolationRecord) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ViolationRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ViolationRecord) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *ViolationRecord) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ScrapeViolationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Violations    []*ViolationRecord     `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeViolationsResponse) Reset() {
	*x = ScrapeViolationsResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeViolationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeViolationsResponse) ProtoMessage() {}

func (x *ScrapeViolationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeViolationsResponse.ProtoReflect.Descriptor instead.
func (*ScrapeViolationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ScrapeViolationsResponse) GetViolations() []*ViolationRecord {
	if x != nil {
		return x.Violations
	}
	return nil
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x18runtimeenforcer.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\x19ListPoliciesStatusRequest\"\x85\x01\n" +
	"\fPolicyStatus\x12;\n" +
	"\x05state\x18\x01 \x01(\x0e2%.runtimeenforcer.agent.v1.PolicyStateR\x05state\x128\n" +
	"\x04mode\x18\x02 \x01(\x0e2$.runtimeenforcer.agent.v1.PolicyModeR\x04mode\"\xe1\x01\n" +
	"\x1aListPoliciesStatusResponse\x12^\n" +
	"\bpolicies\x18\x01 \x03(\v2B.runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntryR\bpolicies\x1ac\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.runtimeenforcer.agent.v1.PolicyStatusR\x05value:\x028\x01\"\x19\n" +
	"\x17ScrapeViolationsRequest\"\xa2\x02\n" +
	"\x0fViolationRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12'\n" +
	"\x0fexecutable_path\x18\x04 \x01(\tR\x0eexecutablePath\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1f\n" +
	"\vpolicy_name\x18\a \x01(\tR\n" +
	"policyName\x12\x14\n" +
	"\x05count\x18\b \x01(\rR\x05count\"e\n" +
	"\x18ScrapeViolationsResponse\x12I\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2).runtimeenforcer.agent.v1.ViolationRecordR\n" +
	"violations*[\n" +
	"\vPolicyState\x12\x1c\n" +
	"\x18POLICY_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12POLICY_STATE_READY\x10\x01\x12\x16\n" +
	"\x12POLICY_STATE_ERROR\x10\x02*[\n" +
	"\n" +
	"PolicyMode\x12\x1b\n" +
	"\x17POLICY_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POLICY_MODE_MONITOR\x10\x01\x12\x17\n" +
	"\x13POLICY_MODE_PROTECT\x10\x022\x90\x02\n" +
	"\rAgentObserver\x12\x81\x01\n" +
	"\x12ListPoliciesStatus\x123.runtimeenforcer.agent.v1.ListPoliciesStatusRequest\x1a4.runtimeenforcer.agent.v1.ListPoliciesStatusResponse\"\x00\x12{\n" +
	"\x10ScrapeViolations\x121.runtimeenforcer.agent.v1.ScrapeViolationsRequest\x1a2.runtimeenforcer.agent.v1.ScrapeViolationsResponse\"\x00B>Z<github.com/neuvector/runtime-enforcer/proto/agent/v1;agentv1b\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(PolicyState)(0),                   // 0: runtimeenforcer.agent.v1.PolicyState
	(PolicyMode)(0),                    // 1: runtimeenforcer.agent.v1.PolicyMode
	(*ListPoliciesStatusRequest)(nil),  // 2: runtimeenforcer.agent.v1.ListPoliciesStatusRequest
	(*PolicyStatus)(nil),               // 3: runtimeenforcer.agent.v1.PolicyStatus
	(*ListPoliciesStatusResponse)(nil), // 4: runtimeenforcer.agent.v1.ListPoliciesStatusResponse
	(*ScrapeViolationsRequest)(nil),    // 5: runtimeenforcer.agent.v1.ScrapeViolationsRequest
	(*ViolationRecord)(nil),            // 6: runtimeenforcer.agent.v1.ViolationRecord
	(*ScrapeViolationsResponse)(nil),   // 7: runtimeenforcer.agent.v1.ScrapeViolationsResponse
	nil,                                // 8: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	0, // 0: runtimeenforcer.agent.v1.PolicyStatus.state:type_name -> runtimeenforcer.agent.v1.PolicyState
	1, // 1: runtimeenforcer.agent.v1.PolicyStatus.mode:type_name -> runtimeenforcer.agent.v1.PolicyMode
	8, // 2: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.policies:type_name -> runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry
	9, // 3: runtimeenforcer.agent.v1.ViolationRecord.timestamp:type_name -> google.protobuf.Timestamp
	6, // 4: runtimeenforcer.agent.v1.ScrapeViolationsResponse.violations:type_name -> runtimeenforcer.agent.v1.ViolationRecord
	3, // 5: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry.value:type_name -> runtimeenforcer.agent.v1.PolicyStatus
	2, // 6: runtimeenforcer.agent.v1.AgentObserver.ListPoliciesStatus:input_type -> runtimeenforcer.agent.v1.ListPoliciesStatusRequest
	5, // 7: runtimeenforcer.agent.v1.AgentObserver.ScrapeViolations:input_type -> runtimeenforcer.agent.v1.ScrapeViolationsRequest
	4, // 8: runtimeenforcer.agent.v1.AgentObserver.ListPoliciesStatus:output_type -> runtimeenforcer.agent.v1.ListPoliciesStatusResponse
	7, // 9: runtimeenforcer.agent.v1.AgentObserver.ScrapeViolations:output_type -> runtimeenforcer.agent.v1.ScrapeViolationsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
