apiVersion: runtimeenforcer.kubewarden.io/v1alpha1
kind: WorkloadPolicyProposal
metadata:
  name: workloadpolicyproposal-sample
spec:
  rulesByContainer:
    opensuse:
      executables:
        allowed:
          - /nginx-ingress-controller
